<?php $currentPage = 'bundle-mockups'; include 'includes/header.php';?>
<!-- Header End -->

<main>
  <section class="banner_section">
    <div class="container">
      <!-- Banner search form -->
      <?php include 'includes/search-form.php';?>
    </div>
  </section>
  <section class="terms_conditions_section">
    <div class="container">
      <div class="heading_col">
        <h1 class="page_heading">PRIVACY POLICY</h1>
        <p>Effective from July 31, 2019</p>
      </div>
      <div class="row_d">
        <div class="terms_conditions_heading no_content"></div>
        <div class="terms_conditions_content">
          <p>
            Effective date: July 31, 2019<br />
            PIXPINE (“us”, “we”, or “our”) operates the
            <a href="http://www.pixpine.com">http://www.pixpine.com</a>
            (hereinafter referred to as the “Service”).<br />
            This page informs you of our policies regarding the collection, use
            and disclosure of personal data when you use our Service and the
            choices you have associated with that data.<br />
            We use your data to provide and improve the Service. By using the
            Service, you agree to the collection and use of information in
            accordance with this policy. Unless otherwise defined in this
            Privacy Policy, the terms used in this Privacy Policy have the same
            meanings as in our Terms and Conditions, accessible from
            <a href="https://www.pixpine.com">https://www.pixpine.com</a><br />
            DEFINITIONS<br />
            Service<br />
            <br />
            Service is the website operated by PIXPINE<br />
            <br />
            Personal Data<br />
            <br />
            Personal Data means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).<br />
            <br />
            Usage Data<br />
            <br />
            Usage Data is data collected automatically either generated by the
            use of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).<br />
            <br />
            Cookies<br />
            <br />
            Cookies are small files stored on your device (computer or mobile
            device).<br />
            <br />
            INFORMATION COLLECTION AND USE<br />
            We collect several different types of information for various
            purposes to provide and improve our Service to you.<br />
            <br />
            TYPES OF DATA COLLECTED<br />
            Personal Data<br />
            <br />
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (“Personal Data”). Personally identifiable information
            may include, but is not limited to:<br />
            <br />
            1- Email address<br />
            2- First name and last name<br />
            3- Cookies and Usage Data<br />
            <br />
            We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials and other information that may be
            of interest to you. You may opt out of receiving any, or all, of
            these communications from us by following the unsubscribe link or
            the instructions provided in any email we send.<br />
            <br />
            Usage Data<br />
            <br />
            We may also collect information on how the Service is accessed and
            used (“Usage Data”). This Usage Data may include information such as
            your computer’s Internet Protocol address (e.g. IP address), browser
            type, browser version, the pages of our Service that you visit, the
            time and date of your visit, the time spent on those pages, unique
            device identifiers and other diagnostic data.<br />
            <br />
            Tracking Cookies Data<br />
            <br />
            We use cookies and similar tracking technologies to track the
            activity on our Service and we hold certain information.<br />
            Cookies are files with a small amount of data which may include an
            anonymous unique identifier. Cookies are sent to your browser from a
            website and stored on your device. Other tracking technologies are
            also used such as beacons, tags and scripts to collect and track
            information and to improve and analyse our Service.<br />
            You can instruct your browser to refuse all cookies or to indicate
            when a cookie is being sent. However, if you do not accept cookies,
            you may not be able to use some portions of our Service.<br />
            <br />
            Examples of Cookies we use:<br />
            <br />
            1- Session Cookies. We use Session Cookies to operate our
            Service.<br />
            2- Preference Cookies. We use Preference Cookies to remember your
            preferences and various settings.<br />
            3- Security Cookies. We use Security Cookies for security
            purposes.<br />
            <br />
            Use of Data<br />
            <br />
            1- To provide and maintain our Service<br />
            2- To notify you about changes to our Service.<br />
            3- To allow you to participate in interactive features of our
            Service when you choose to do so<br />
            4- To provide customer support<br />
            5- To gather analysis or valuable information so that we can improve
            our Service<br />
            6- To monitor the usage of our Service<br />
            7- To detect, prevent and address technical issues<br />
            8- To provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information<br />
            <br />
            Disclosure of Data<br />
            <br />
            Legal Requirements<br />
            PIXPINE may disclose your Personal Data in the good faith belief
            that such action is necessary to:<br />
            <br />
            1- To comply with a legal obligation<br />
            2- To protect and defend the rights or property of PIXPINE<br />
            3- To prevent or investigate possible wrongdoing in connection with
            the Service<br />
            4- To protect the personal safety of users of the Service or the
            public<br />
            5- To protect against legal liability<br />
            <br />
            Security of Data<br />
            <br />
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.<br />
            <br />
            SERVICE PROVIDERS<br />
            We may employ third party companies and individuals to facilitate
            our Service (“Service Providers”), provide the Service on our
            behalf, perform Service-related services or assist us in analysing
            how our Service is used. These third parties have access to your
            Personal Data only to perform these tasks on our behalf and are
            obligated not to disclose or use it for any other purpose.<br />
            <br />
            ANALYTICS<br />
            We may use third-party Service Providers to monitor and analyse the
            use of our Service.<br />
            <br />
            GOOGLE ANALYTICS<br />
            Google Analytics is a web analytics service offered by Google that
            tracks and reports website traffic. Google uses the data collected
            to track and monitor the use of our Service. This data is shared
            with other Google services. Google may use the collected data to
            contextualise and personalise the ads of its own advertising
            network. You can opt-out of having made your activity on the Service
            available to Google Analytics by installing the Google Analytics
            opt-out browser add-on. The add-on prevents the Google Analytics
            JavaScript (ga.js, analytics.js and dc.js) from sharing information
            with Google Analytics about visits activity. For more information on
            the privacy practices of Google, please visit the Google Privacy
            Terms web page:
            <a href="https://policies.google.com/privacy?hl=en"
              >https://policies.google.com/privacy?hl=en</a
            ><br />
            <br />
            PAYMENTS<br />
            We may provide paid products and/or services within the Service. In
            that case, we use third-party services for payment processing (e.g.
            payment processors). We will not store or collect your payment card
            details. That information is provided directly to our third-party
            payment processors whose use of your personal information is
            governed by their Privacy Policy. These payment processors adhere to
            the standards set by PCI-DSS as managed by the PCI Security
            Standards Council, which is a joint effort of brands like Visa,
            MasterCard, American Express and Discover. PCI-DSS requirements help
            ensure the secure handling of payment information. The payment
            processors we work with are: 2Checkout Their Privacy Policy can be
            viewed at
            <a href="https://www.2checkout.com/policies/privacy-policy">
              https://www.2checkout.com/policies/privacy-policy </a
            ><br />
            <br />
            LINKS TO OUR SITES<br />
            Our Service may contain links to other sites that are not operated
            by us. If you click a third party link, you will be directed to that
            third party’s site. We strongly advise you to review the Privacy
            Policy of every site you visit. We have no control over and assume
            no responsibility for the content, privacy policies or practices of
            any third party sites or services.<br />
            <br />
            CHILDREN’S PRIVACY<br />
            Our Service does not address anyone under the age of 18
            (“Children”). We do not knowingly collect personally identifiable
            information from anyone under the age of 18. If you are a parent or
            guardian and you are aware that your Child has provided us with
            Personal Data, please contact us. If we become aware that we have
            collected Personal Data from children without verification of
            parental consent, we take steps to remove that information from our
            servers.<br />
            <br />
            CHANGES TO THIS PRIVACY POLICY<br />
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
            We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update the
            “effective date” at the top of this Privacy Policy. You are advised
            to review this Privacy Policy periodically for any changes. Changes
            to this Privacy Policy are effective when they are posted on this
            page.<br />
            <br />
            CONTACT US<br />
            If you have any questions about this Privacy Policy, please contact
            us by email:<br />
            <br />
            <a href="mailto:support@pixpine.com">support@pixpine.com</a>
          </p>
        </div>
      </div>
    </div>
  </section>
</main>

<!-- Footer -->
<?php include 'includes/footer.php';?>
